name: Tea Is Fantastic
on:
  push:
    branches: [ "workflow" ]
  workflow_dispatch:

env:
  OUTPUT_PATH: '${{ github.workspace }}/output'
  DATA_PATH: '${{ github.workspace }}/data'
  APP_PATH: '${{ github.workspace }}/app'
  ANDROID_PATH: '${{ github.workspace }}/output/android'
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: halaat
    steps:
      - uses: actions/checkout@v3

      - name: Clone repo
        run: |
          mkdir ${{ env.APP_PATH }}
          cd ${{ env.APP_PATH }}
          git clone https://github.com/tea-is-fantastic/tea-is-fantastic.git .

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Python stuff
        working-directory: ${{ env.APP_PATH }}
        run: |
          mkdir ${{ env.OUTPUT_PATH }}
          pip install -r ${{ env.APP_PATH }}/requirements.txt
          python ${{ env.APP_PATH }}/scripts/main.py

      - name: Build bundle
        working-directory: ${{ env.OUTPUT_PATH }}
        run: | 
          mkdir android/app/src/main/assets
          npx react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/release/
#          npx react-native bundle --dev false --platform android --entry-file index.js --bundle-output ${{ env.ANDROID_PATH }}/app/src/main/assets/index.android.bundle --assets-dest ${{ env.ANDROID_PATH }}/app/src/main/res

      - name: Build apk
        working-directory: ${{ env.ANDROID_PATH }}
        run: rm -rf ./app/src/main/res/drawable-* && rm -rf ./app/src/main/res/raw/* && ./gradlew assembleRelease
          

      - name: Sign apk
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: '${{ env.ANDROID_PATH }}/app/build/outputs/apk/release'
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}

      - run: cp ${{ env.ANDROID_PATH }}/app/build/outputs/apk/release/app-release.apk ${{ env.OUTPUT_PATH }}

      - name: Push changes
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'output'
          destination-github-username: 'asfandyarsheikh'
          destination-repository-name: 'asfandyar-expo'
          user-email: github-actions[bot]@users.noreply.github.
          user-name: github-actions[bot]
          target-branch: main